### ISSUE TITLE
Icona Prints: non vedo più le operazioni fatte, mi dà solo il titolo della pagina. L'anno scorso invece avevo fatto le stampe semza problema. Volevo sapere se è un errore oppure state lavorandoci sopra? 

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#2]
Icona Prints: non vedo più le operazioni fatte, mi dà solo il titolo della pagina. L'anno scorso invece avevo fatto le stampe semza problema. Volevo sapere se è un errore oppure state lavorandoci sopra?

**Comment by faberyx** [comment]
adesso mi pare che funziona

**Comment by marcochiavacci** [comment]
il problema che per default ti fa vedere solo quelle dall'ultima chiusura ecco perche, ma mettendo ora la data dal/al non prende piu un considerazione la data di chiusura
