### ISSUE TITLE
Agg le valute

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#27]
halyna slyvych
Come faccio ad aggiungere delle valute non presenti nell'elenco (icona Currency, Show All)? Per es noi abbiamo anche UAH, EGP, ARG (peso argentino ho cancellato per caso io)
19 days ago
italo sorbara
Per accordi per le vie brevi con Paolo evidenziamo che questa segnalazione potrebbe essere un bug o la non conoscenza di una funzione non documentata in un manuale d'uso

**Comment by faberyx** [comment]
dal bottone add-currency
