### ISSUE TITLE
accendo la chiusura (icona Close daily acc), dopo aver contato le valute mossi quando si clicca su Check All per vede se ci sono le differenze tra valori reali e quelli di contabilità c'è un errore per quanto riguarda le valute (non euro). Colonna Money total indica il valore reale di soldi (quello che ho contato), la colonna Total indica quello della confrontabilità (quello che dovrei avere). Attualmente però questa ultima indica il controvalore della valuta in euro come potete veder con Usd sull'imagine. 

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#3]
accendo la chiusura (icona Close daily acc), dopo aver contato le valute mossi quando si clicca su Check All
per vede se ci sono le differenze tra valori reali e quelli di contabilità c'è un errore per quanto riguarda le valute (non euro). Colonna Money total indica il valore reale di soldi (quello che ho contato), la colonna Total indica quello della confrontabilità (quello che dovrei avere). Attualmente però questa ultima indica il controvalore della valuta in euro come potete veder con Usd sull'imagine. 
![save-balance-differenze1419244388](https://cloud.githubusercontent.com/assets/10194847/5798452/84b4e322-9fc7-11e4-994a-19aa00979fb6.jpg)

**Comment by faberyx** [comment]
questo e' stato corretto
