### ISSUE TITLE
Close daily Account - Operation details

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#5]
Per quanto riguarda icona Oper. Det che appare cliccando sul movimento nelle colonne Transf. In/Out:
manca il chiarimento dove vanno finire o da dove provengono i soldi. Per esempio sul jpg allegato potete vedere che ci sono stati 2 trasferimenti di Eur Not, entrambi in uscità (sell) però non è chiaro dove sono andati. 100 euro sono stati trasferiti in altra cassa( C.F. ) e altri 100 in altro ufficio (Stamperia) però in questa icona non si vede. La stessa cosa se fossero entrati (buy) non si vedrebbe da dove provengono

**Comment by marcochiavacci** [comment]
![operation-details-contabilita1419000188](https://cloud.githubusercontent.com/assets/10194847/5798659/e33370c4-9fc9-11e4-92b5-19e0ffd8bc45.jpg)

**Comment by faberyx** [comment]
i trsferimenti hanno una loro finestra dove e' specificato il from e to
