### ISSUE TITLE
vendita in banca travel cheque

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#7]
certe volte non riesco fare le vendite in banca, purtroppo non sono riuscita a capire che cosa esattamente blocca il sistema. Spiego sul esempio:
Ho inserito in cassa 1000 USD TCH (non comprato ma inserito tramite cash managment). Ho provato venderli in banca. Vendendo 1000 si verificato un errore (guarda allegato), pero non ho avuto problemi ad vendere 500. Ho venduto senza problemi USD not però non USD TCH, non so se è legato all'importo o al tipo di valuta (not o tch).
Inoltre mi ha creato una gran confusione in contabilità: in secondo allegato (la chiusura) in cassa come saldo finale mi risultano 0 usd not (guarda sottfondo), nel icona di controllo 588 (icona in primo piano). 
![chiusura1418754063](https://cloud.githubusercontent.com/assets/10194847/5798502/0d29cc54-9fc8-11e4-889f-ab9547076dfe.jpg)
![sell-banca-errore1418754061](https://cloud.githubusercontent.com/assets/10194847/5798501/0d2467c8-9fc8-11e4-8bf7-905e50b453dd.jpg)

**Comment by faberyx** [comment]
questo mi pare che lo avevo risolto
