### ISSUE TITLE
riconoscimento cliente registrato

### ISSUE THREAD

**Issue by marcochiavacci** [faberyx/paloma#8]
facendo l'operazione al nome di cliente già presente in anagrafe (icona Customers) il programma non riconosce il tale nome come registrato. In realtà credo che me lo fa vedere però per una frazione di secondo e allora non riesco inserirlo e come risultato viene registrato seconda volta 
![icona-buy-sell1418747685](https://cloud.githubusercontent.com/assets/10194847/5798517/30c53d6a-9fc8-11e4-9da5-11cea1977566.jpg)

**Comment by faberyx** [comment]
per selezionare il cliente bisogna andare sopra il nome con le frecce e premere invio
